/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ContentImage = {
  _type: "contentImage";
  asset: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  caption?: string;
  displayStyle?: "cover" | "contain-padded" | "contain";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        openInNewTab?: boolean;
        nofollow?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ContentImage)
>;

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type UseCase = {
  _id: string;
  _type: "useCase";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  introduction: string;
  brandOrigin: string;
  industry: string;
  categoryRef?: CategoryReference;
  targetMarket: string;
  challenge: string;
  deliverables: Array<string>;
  outcomeTitle: string;
  outcomeDescription: string;
  whyItWorked: string;
  showOnHomepage?: boolean;
  displayOrder: number;
  migrationSource?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
  publishedAt: string;
  author?: AuthorReference;
  categoryRef?: CategoryReference;
  category?: string;
  coverImage: ContentImage;
  body: BlockContent;
  seoTitle?: string;
  seoDescription?: string;
  migrationSource?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role?: string;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  shortBio?: string;
  ctaButtonText?: string;
  ctaUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ContentImage
  | BlockContent
  | CategoryReference
  | UseCase
  | Slug
  | AuthorReference
  | BlogPost
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/lib/sanity/queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current)] | order(publishedAt desc, _id asc) {    _id, title, "slug": slug.current, description, publishedAt,    "category": select(defined(categoryRef) => categoryRef->title, category),    author->{_id, name, slug, role, profileImage, shortBio, ctaButtonText, ctaUrl},    coverImage, body, seoTitle, seoDescription  }
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string;
  publishedAt: string;
  category: string | null;
  author: {
    _id: string;
    name: string;
    slug: Slug;
    role: string | null;
    profileImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
    shortBio: string | null;
    ctaButtonText: string | null;
    ctaUrl: string | null;
  } | null;
  coverImage: ContentImage;
  body: BlockContent;
  seoTitle: string | null;
  seoDescription: string | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: CASE_STUDIES_QUERY
// Query: *[_type == "useCase"] | order(displayOrder asc, _id asc) {    _id, title, "slug": coalesce(slug.current, _id), introduction, brandOrigin, industry, targetMarket, challenge,    "category": select(defined(categoryRef) => categoryRef->title, industry),    deliverables, outcomeTitle, outcomeDescription, whyItWorked  }
export type CASE_STUDIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  introduction: string;
  brandOrigin: string;
  industry: string;
  targetMarket: string;
  challenge: string;
  category: string;
  deliverables: Array<string>;
  outcomeTitle: string;
  outcomeDescription: string;
  whyItWorked: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "blogPost" && defined(slug.current)] | order(publishedAt desc, _id asc) {\n    _id, title, "slug": slug.current, description, publishedAt,\n    "category": select(defined(categoryRef) => categoryRef->title, category),\n    author->{_id, name, slug, role, profileImage, shortBio, ctaButtonText, ctaUrl},\n    coverImage, body, seoTitle, seoDescription\n  }\n': BLOG_POSTS_QUERY_RESULT;
    '\n  *[_type == "useCase"] | order(displayOrder asc, _id asc) {\n    _id, title, "slug": coalesce(slug.current, _id), introduction, brandOrigin, industry, targetMarket, challenge,\n    "category": select(defined(categoryRef) => categoryRef->title, industry),\n    deliverables, outcomeTitle, outcomeDescription, whyItWorked\n  }\n': CASE_STUDIES_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
